<div class="article">

    <div class="article-title">
        <h2>
            O PHP planeti
        </h2>
    </div>

    <div class="article-content">
        <p>
	Lorem ipsum test dolor sit amet, consec tetur adipiscing elit. Nullam viverra, diam et tristique tempor, ligula metus consectetur elit, ac fermentum tortor nibh in dui. Donec sem mi, congue id fringilla eu, scelerisque in tellus. Fusce eget pellentesque massa. Proin id tortor vitae arcu aliquam auctor a eget dui. Cras non eros eget justo dapibus vestibulum. Vestibulum rutrum, sapien quis congue viverra, justo sapien auctor augue, sit amet sodales velit elit id ligula. Donec fringilla mi in nisi laoreet pellentesque. Ut pellentesque, diam quis lacinia ultrices, purus odio pretium dui, id elementum quam erat at ante. Aenean ultricies dignissim ipsum, eget mattis odio tincidunt at. Cras elementum arcu sit amet augue rhoncus vel mattis augue volutpat. Proin vehicula euismod magna.
        </p>
        <p>
	Nunc consequat nibh sed nisl venenatis nec congue leo suscipit. Nulla facilisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas metus nisi, consequat vel ullamcorper et, fermentum et mi. Pellentesque accumsan nibh in augue consectetur volutpat. Phasellus porta ultricies ullamcorper. Etiam venenatis pharetra sem, in consectetur nisi lacinia sed. Fusce ut enim mi, accumsan ullamcorper sem. Fusce nibh lectus, aliquet in posuere id, adipiscing nec nisl. Pellentesque vestibulum ultricies porta.
        </p>
    </div>

</div>