<div class="article">

    <div class="article-title">
        <h2>
            O PHP planeti
        </h2>
    </div>

    <div class="article-content">
        <p>
            PHP planeta je projekat koji ima za cilj da stvori zajednicu
            PHP programera iz Srbije i regiona, da približi programerima
            novosti iz sveta PHP-a i ostalih alata i programa koje jedan
            PHP programer koristi u svom svakodnevnom radu.
        </p>

        <p>
            Za dalji razvoj planete postoji nekoliko ideja, ali kako je ovo
            projekat na kojem se radi u slobodno vreme, kada i koje ideje
            će se realizovati, ostaje da se vidi.
        </p>

        <p>
            Glavni i, zasada, jedini programer, koder, autor iza planete je
            Robert Bašić.
        </p>
    </div>

</div>