<div class="article">

    <div class="article-title">
        <h2>
            Kontakt
        </h2>
    </div>

    <div class="article-content">
        <p>
            Ukoliko želiš stupiti u kontak možeš to učiniti pomoću kontakt
            forme ispod ili slanjem Email-a na: <strong>phpplaneta [at] gmail [dot] com</strong>.
            <br />
            Kako je ovo projekat na kojem radim u slobodno vreme, može se desiti
            da odgovor neće baš brzo stići ;)
        </p>
    </div>

</div>

<?php echo $this->flashMessenger(); ?>

<div id="contact">
    <?php echo $this->contactForm; ?>
</div>