<?php if(count($this->comments) > 0): ?>
<table>
    <thead>
        <tr>
            <th>Ime</th>
            <th>E-mail</th>
            <th>URL</th>
            <th>Datum</th>
            <th>Aktivno?</th>
            <th colspan="2">Akcija</th>
        </tr>
    </thead>
    <?php foreach($this->comments as $comment): ?>
    <tr style="background-color:<?php echo $this->cycle(array("#FFFFFF","#F1F1F1"))->next()?>">
        <td>
            <?php echo $this->escape($comment->name); ?>
        </td>

        <td>
            <?php echo $this->escape($comment->email); ?>
        </td>

        <td>
            <?php echo $this->escape($comment->url); ?>
        </td>

        <td>
            <?php echo $this->escape($comment->datetime_added); ?>
        </td>

        <td>
            <?php if($comment->active == 1): ?>
                &#10004;
            <?php else: ?>
                &#10008;
            <?php endif; ?>
        </td>

        <td>
            <a href="<?php echo $this->url(array(
                                            'action' => 'edit',
                                            'controller' => 'news-comments',
                                            'id' => $comment->id
                                        ),
                                        'admin', true); ?>">Izmeni</a>
        </td>
        <td>
            <a class="delete" href="<?php echo $this->url(array(
                                            'action' => 'delete',
                                            'controller' => 'news-comments',
                                            'id' => $comment->id
                                        ),
                                        'admin', true); ?>">Obriši</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>

<?php echo $this->paginationControl($this->comments, 'Sliding', 'paginator.phtml'); ?>

<?php else: ?>
Nema komentara
<?php endif; ?>