<a href="<?php echo $this->crumb['root']['href']; ?>" class="<?php echo $this->crumb['root']['class']; ?>">
    <?php echo $this->crumb['root']['title']; ?>
</a>
>
<a href="<?php echo $this->crumb['first']['href']; ?>" class="<?php echo $this->crumb['first']['class']; ?>">
    <?php echo $this->crumb['first']['title']; ?>
</a>
<?php if(isset($this->crumb['second'])): ?>
>
<a href="<?php echo $this->crumb['second']['href']; ?>" class="<?php echo $this->crumb['second']['class']; ?>">
    <?php echo $this->crumb['second']['title']; ?>
</a>
<?php endif; ?>