<?php if ($this->pageCount): ?>

<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
    <a href="<?php echo $this->url(array('page' => $this->first), 'homePagination'); ?>"> &laquo; </a>
    <a href="<?php echo $this->url(array('page' => $this->previous), 'homePagination'); ?>"> &lsaquo; </a>
<?php else: ?>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('page' => $page), 'homePagination'); ?>"> <?php echo $page; ?> </a>
  <?php else: ?>
    <span class="disabled"> <?php echo $page; ?> </span>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next), 'homePagination'); ?>"> &rsaquo; </a>
  <a href="<?php echo $this->url(array('page' => $this->last), 'homePagination'); ?>"> &raquo; </a>
<?php endif; ?>
</div>

<?php endif; ?>