<?php if ($this->pageCount): ?>

<?php if($this->keyword != '') {
    $linkAdd = '/?keyword=' . $this->escape($this->keyword);
} else {
    $linkAdd = '';
}
?>

<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
    <a href="<?php echo $this->url(array('page' => $this->first)) . $linkAdd; ?>"> &laquo; </a>
    <a href="<?php echo $this->url(array('page' => $this->previous)) . $linkAdd; ?>"> &lsaquo; </a>
<?php else: ?>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('page' => $page)) . $linkAdd; ?>"> <?php echo $page; ?> </a>
  <?php else: ?>
    <span class="disabled"> <?php echo $page; ?> </span>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)) . $linkAdd; ?>"> &rsaquo; </a>
  <a href="<?php echo $this->url(array('page' => $this->last)) . $linkAdd; ?>"> &raquo; </a>
<?php endif; ?>
</div>

<?php endif; ?>