<div>
    <a href="<?php echo $this->url(
                                array(
                                    'action' => 'add',
                                    'controller' => 'news-sources'
                                ),
                                'admin', true); ?>">Dodaj izvor</a>
</div>

<?php if(count($this->sources) > 0): ?>
<table>
    <thead>
        <tr>
            <th>Naziv</th>
            <th>URL</th>
            <th colspan="2">Akcija</th>
        </tr>
    </thead>
    <?php foreach($this->sources as $source): ?>
    <tr style="background-color:<?php echo $this->cycle(array("#FFFFFF","#F1F1F1"))->next()?>">
        <td>
            <?php echo $this->escape($source->name); ?>
        </td>

        <td>
            <?php echo $this->escape($source->url); ?>
        </td>

        <td>
            <a href="<?php echo $this->url(array(
                                            'action' => 'edit',
                                            'controller' => 'news-sources',
                                            'id' => $source->id
                                        ),
                                        'admin', true); ?>">Izmeni</a>
        </td>
        <td>
            <a class="delete" href="<?php echo $this->url(array(
                                            'action' => 'delete',
                                            'controller' => 'news-sources',
                                            'id' => $source->id
                                        ),
                                        'admin', true); ?>">Obriši</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>

<?php echo $this->paginationControl($this->sources, 'Sliding', 'paginator.phtml'); ?>

<?php else: ?>
Nema izvora vesti
<?php endif; ?>