Okruženje: <?php echo $this->environment; ?>
<br />
Full page cache: <?php if($this->fullpageCacheSetting): ?>Uključeno<?php else: ?>Isključeno<?php endif; ?>
<br />
DB cache: <?php if($this->dbCacheSetting): ?>Uključeno<?php else: ?>Isključeno<?php endif; ?>
<br />
Log: <?php if($this->logSetting): ?>Uključeno<?php else: ?>Isključeno<?php endif; ?>
<br />
<a href="<?php echo $this->url(array(
                                'action' => 'admin-list',
                                'controller' => 'logs'),
                                'admin', true); ?>">Logovi</a>