<a href="<?php echo $this->url(array(
                                    'action' => 'add',
                                    'controller' => 'news'
                                ),
                                'admin', true); ?>">Add</a>

<br />

<?php if(count($this->news) > 0): ?>

    <?php foreach($this->news as $news): ?>

        <?php echo $this->escape($news->title); ?>

        <a href="<?php echo $this->url(array(
                                            'action' => 'edit',
                                            'controller' => 'news',
                                            'id' => $news->id
                                        ),
                                        'admin', true); ?>">Edit</a>
        <a href="<?php echo $this->url(array(
                                            'action' => 'delete',
                                            'controller' => 'news',
                                            'id' => $news->id
                                        ),
                                        'admin', true); ?>">Delete</a>

        <br />
    <?php endforeach; ?>

<?php else: ?>
Nema vesti
<?php endif; ?>