<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>

        <link rel="stylesheet" href="/static/css/reset.css" type="text/css" />
        <link rel="stylesheet" href="/static/css/text.css" type="text/css" />
        <link rel="stylesheet" href="/static/css/960.css" type="text/css" />
        <link rel="stylesheet" href="/static/css/public.css" type="text/css" />

        <?php echo $this->headScript(); ?>

    </head>

    <body>

        <div id="page" class="container_16">

            <div id="header" class="grid_16">

            </div>

            <div id="body" class="container_16">

                <div id="left" class="grid_11">
                    <?php
                        echo $this->layout()->content;
                    ?>
                </div>

                <div id="right" class="grid_5">

                    <div>
                        <form name="search" action="<?php echo $this->url(array(
                            'action' => 'search',
                            'controller' => 'news'
                            ), '', true); ?>" method="get">
                            <input type="text" name="keyword" />
                        </form>
                    </div>

                    <div>
                        <?php echo $this->mostUsedTags(); ?>
                    </div>

                </div>

            </div>

        </div>

    </body>
</html>