<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>

        <link rel="stylesheet" href="/static/css/reset.css" type="text/css" />
        <link rel="stylesheet" href="/static/css/text.css" type="text/css" />
        <link rel="stylesheet" href="/static/css/960.css" type="text/css" />
        <link rel="stylesheet" href="/static/css/public.css" type="text/css" />

        <?php echo $this->headLink(); ?>

        <?php echo $this->jQuery(); ?>

        <?php echo $this->headScript(); ?>

    </head>

    <body>

        <div id="page" class="container_16">

            <div id="header" class="grid_16">
                <ul class="navigation">
                    <li>
                        <a href="<?php echo $this->url(array(
                                                'action' => 'index',
                                                'controller' => 'index'),
                                                '', true); ?>">Početna</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array(
                                                'action' => 'browse',
                                                'controller' => 'news',
                                                'category' => 'vesti'),
                                                '', true); ?>">Vesti</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array(
                                                'action' => 'about',
                                                'controller' => 'index'),
                                                '', true); ?>">O PHP planeti</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array(
                                                'action' => 'contact',
                                                'controller' => 'index'),
                                                 '', true); ?>">Kontakt</a>
                    </li>
                </ul>
            </div>

            <div id="body" class="container_16">

                <div id="left" class="grid_11">

                    <?php echo $this->breadcrumbs(); ?>

                    <?php
                        echo $this->layout()->content;
                    ?>
                </div>

                <div id="right" class="grid_5">

                    <div>
                        <form name="search" action="<?php echo $this->url(array(
                            'action' => 'search',
                            'controller' => 'news'
                            ), '', true); ?>" method="get">
                            <input type="text" name="keyword" />
                        </form>
                    </div>

                    <div>
                        <?php echo $this->mostUsedTags(); ?>
                    </div>

                    <div id="calendar"></div>

                </div>

            </div>

        </div>

        <script type="text/javascript" src="/static/js/calendar.js"></script>

    </body>
</html>