<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>

        <link rel="stylesheet" href="/static/css/reset.css" type="text/css" />
        <link rel="stylesheet" href="/static/css/text.css" type="text/css" />
        <link rel="stylesheet" href="/static/css/960.css" type="text/css" />
        <link rel="stylesheet" href="/static/css/public.css" type="text/css" />

        <?php echo $this->headLink(); ?>

        <?php echo $this->jQuery(); ?>

        <?php echo $this->headScript(); ?>

    </head>

    <body>

        <div id="header">
            <div id="logo" class="container_16">
                <a href="/">
                    <img src="/static/img/logo.jpg" alt="PHPPlaneta.net" />
                </a>
            </div>
        </div>

        <div id="page" class="container_16">

            <ul class="navigation">
                <li class="active">
                    <a href="<?php echo $this->url(array(
                                            'action' => 'index',
                                            'controller' => 'index'),
                                            '', true); ?>">Početna</a>
                </li>
                <li>
                    <a href="<?php echo $this->url(array(
                                            'action' => 'browse',
                                            'controller' => 'news',
                                            'category' => 'vesti'),
                                            '', true); ?>">Vesti</a>
                    <ul>
                        <li>
                            <a href="#">
                                Sub 1
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Sub 1
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="<?php echo $this->url(array(
                                            'action' => 'about',
                                            'controller' => 'index'),
                                            '', true); ?>">O planeti</a>
                </li>
                <li>
                    <a href="<?php echo $this->url(array(
                                            'action' => 'contact',
                                            'controller' => 'index'),
                                             '', true); ?>">Kontakt</a>
                </li>
            </ul>

            <div id="body" class="container_16">

                <div id="left" class="grid_11">

                    <div class="breadcrumbs">
                        <?php echo $this->breadcrumbs(); ?>
                    </div>

                    <?php
                        echo $this->layout()->content;
                    ?>
                </div>

                <div id="right" class="grid_5">

                    <div id="search">
                        <form name="search" action="<?php echo $this->url(array(
                            'action' => 'search',
                            'controller' => 'news'
                            ), '', true); ?>" method="get">
                            <input type="text" name="keyword" class="search-field" />
                            <input type="image" name="search" src="/static/img/search.jpg" class="search-image" />
                        </form>
                    </div>

                    <div id="social">
                        <a href="http://twitter.com/phpplaneta" class="twitter">
                            <img src="/static/img/twitter.jpg" alt="Prati na Twitter-u" />
                        </a>

                        <a href="/news/rss" class="rss">
                            <img src="/static/img/rss.jpg" alt="Preuzmi RSS feed" />
                        </a>
                    </div>

                    <div id="calendar"></div>

                    <div id="banners">
                        <div class="banner">
                            <a href="<?php echo $this->url(array(
                                            'action' => 'contact',
                                            'controller' => 'index'),
                                             '', true); ?>">
                            <img src="/static/img/banner1.jpg" alt="banner" />
                            </a>
                        </div>
                        
                        <div class="banner">
                            <a href="<?php echo $this->url(array(
                                            'action' => 'contact',
                                            'controller' => 'index'),
                                             '', true); ?>">
                            <img src="/static/img/banner2.jpg" alt="banner" />
                            </a>
                        </div>
                    </div>

                    <div id="tag-cloud">
                        <h4>Oznake</h4>
                        <?php echo $this->mostUsedTags(); ?>
                    </div>

                </div>

            </div>

        </div>

        <script type="text/javascript" src="/static/js/calendar.js"></script>
        <script type="text/javascript" src="/static/js/script.js"></script>

    </body>
</html>